### ISSUE TITLE
The background won't change

### ISSUE THREAD

**Issue by Arandolf** [astize/redrock#1]
![screenshot from 2019-02-10 09-11-25](https://user-images.githubusercontent.com/46224289/52531868-24b5c980-2d14-11e9-8f55-c7e6e3eb4bfb.png)

As you can see from these screenshots, I inserted the background as in the read.me file, but in sddm only a white background is shown. How can I solve? Thanks in advance (sorry for my bad en)

EDIT: if i reinstall the theme, the default background isn't displayed

**Comment by valters-tomsons** [comment]
Hey, I'm having the same issue - having a white background even with the default image. How did you solve this?

**Comment by Arandolf** [comment]
i didn't lol
i just changed the theme

**Comment by valters-tomsons** [comment]
Thanks, me too :1st_place_medal:

**Comment by benlarkins** [comment]
To solve this issue open `redrock/Main.qml` in your text editor of choice and change the line with `source: "images/background.jpg"` to `source: "images/background.png"`
